"""
LangGraph State Definition
===========================
Defines the shared state that flows through all agent nodes
in the surveillance pipeline.
"""

from typing import Annotated, Any
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class Detection(TypedDict):
    """A single object detection from YOLOv8."""
    class_id: int
    class_name: str
    confidence: float
    bbox: list[int]        # [x1, y1, x2, y2]
    center: list[int]      # [cx, cy]


class TrackedObject(TypedDict):
    """An object with a persistent track ID."""
    track_id: int
    class_id: int
    class_name: str
    confidence: float
    bbox: list[int]        # [x1, y1, x2, y2]
    center: list[int]      # [cx, cy]
    velocity: float        # pixels/frame displacement
    frames_tracked: int    # how many frames this ID has been seen


class Anomaly(TypedDict):
    """A detected anomaly event."""
    anomaly_type: str      # "crowd", "loitering", "speed", "zone_intrusion", "new_object"
    severity: str          # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    description: str
    involved_objects: list[dict]
    location: list[int]    # [x, y] approximate center of anomaly
    frame_id: int
    timestamp: str


class Alert(TypedDict):
    """An alert generated by the action agent."""
    alert_id: str
    anomaly: Anomaly
    llm_analysis: str
    recommended_action: str
    timestamp: str


class SurveillanceState(TypedDict):
    """
    The main state object passed through the LangGraph pipeline.

    Each node reads from and writes to specific fields:
    - vision_node    → writes: detections, tracked_objects
    - anomaly_node   → writes: anomalies
    - reasoning_node → writes: llm_analysis, messages
    - action_node    → writes: alerts
    """
    # ── Video Frame Data ──
    frame_bytes: bytes                                  # JPEG-encoded frame (for serialization)
    frame_id: int                                       # Frame counter
    timestamp: str                                      # ISO 8601 timestamp

    # ── Detection & Tracking ──
    detections: list[Detection]                         # Raw YOLOv8 detections
    tracked_objects: list[TrackedObject]                 # Objects with persistent IDs
    person_count: int                                   # Number of people detected

    # ── Anomaly Detection ──
    anomalies: list[Anomaly]                            # Detected anomalies this frame
    has_anomaly: bool                                   # Flag for conditional routing

    # ── LLM Reasoning ──
    llm_analysis: str                                   # Groq LLM analysis text
    messages: Annotated[list[BaseMessage], add_messages] # LangGraph message history

    # ── Alerts ──
    alerts: list[Alert]                                 # Generated alerts

    # ── Metadata ──
    frame_shape: list[int]                              # [height, width, channels]
    fps: float                                          # Current FPS
